export const appConstants = {
    COVID_SUMMARY_REQUEST: 'COVID_SUMMARY_REQUEST',
    COVID_SUMMARY_SUCCESS: 'COVID_SUMMARY_SUCCESS',

    OVERALL_REPORT_REQUEST: 'OVERALL_REPORT_REQUEST',
    OVERALL_REPORT_SUCCESS: 'OVERALL_REPORT_SUCCESS',

    STATE_REPORT_REQUEST: 'STATE_REPORT_REQUEST',
    STATE_REPORT_SUCCESS: 'STATE_REPORT_SUCCESS',

    
    DAILY_REPORT_REQUEST: 'DAILY_REPORT_REQUEST',
    DAILY_REPORT_SUCCESS: 'DAILY_REPORT_SUCCESS',
}